parameters:
    legacy_dsn: sqlite://:memory:
    anonymous_user_id: 10
    kernel.debug: false
    languages: []
    image_storage_prefix: images
    binaryfile_storage_prefix: binary
    storage_dir: var/ezdemo_site/storage
    ignored_storage_files:
        -
            var/ezdemo_site/storage/images/design/plain-site/172-2-eng-US/eZ-Publish-Demo-Design-without-demo-content1.png

    ezpublish.cache_pool.spi.cache.decorator.class: eZ\Publish\Core\Persistence\Cache\Tests\Helpers\IntegrationTestCacheServiceDecorator

services:
    ezpublish.cache_pool.spi.cache.decorator:
        class: %ezpublish.cache_pool.spi.cache.decorator.class%
