parameters:
    ezpublish.cache_pool.class: Stash\Pool
    ezpublish.cache_pool.factory.class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\CacheFactory
    ezpublish.cache_pool.spi.cache.decorator.class: eZ\Publish\Core\Persistence\Cache\CacheServiceDecorator

services:
    ezpublish.cache_pool:
        class: %ezpublish.cache_pool.class%
        factory_service: ezpublish.cache_pool.factory
        factory_method: getCachePool
        arguments: [@ezpublish.config.resolver]

    ezpublish.cache_pool.factory:
        class: %ezpublish.cache_pool.factory.class%
        calls:
            - [setContainer, [@service_container]]

    ezpublish.cache_pool.spi.cache.decorator:
        class: %ezpublish.cache_pool.spi.cache.decorator.class%
        arguments: [@ezpublish.cache_pool]
