parameters:
    ezpublish.persistence.field_type_registry.class: eZ\Publish\Core\Persistence\FieldTypeRegistry
    ezpublish.persistence.slug_converter.class: eZ\Publish\Core\Persistence\Legacy\Content\UrlAlias\SlugConverter

services:
    # TODO
    ezpublish.persistence.field_type_registry:
        class: %ezpublish.persistence.field_type_registry.class%

    ezpublish.persistence.slug_converter:
        class: %ezpublish.persistence.slug_converter.class%
        arguments: [@ezpublish.api.storage_engine.transformation_processor]
